name: SchoolBot Scheduler

on:
  schedule:
    - cron: "0 22 * * *"   # 한국 시간 07:00 (UTC 기준 22:00)
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SchoolBot
        env:
          NEIS_API_KEY: ${{ secrets.NEIS_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python schoolbot.py
